library(testthat)

context("ChiSquared distribution")

test_that("properties & traits", {
  expect_equal(ChiSquared$new()$valueSupport(), "continuous")
  expect_equal(ChiSquared$new()$variateForm(), "univariate")
  expect_equal(ChiSquared$new()$symmetry(), "asymmetric")
  expect_equal(ChiSquared$new()$sup(), Inf)
  expect_equal(ChiSquared$new()$inf(), 0)
  expect_equal(ChiSquared$new()$dmax(), Inf)
  expect_equal(ChiSquared$new()$dmin(), 0)
})

chi <- ChiSquared$new(df = 8)
test_that("statistics", {
  expect_equal(chi$mean(), 8)
  expect_equal(chi$var(), 16)
  expect_equal(chi$skewness(), 1)
  expect_equal(chi$kurtosis(TRUE), 1.5)
  expect_equal(chi$kurtosis(FALSE), 4.5)
  expect_equal(round(chi$entropy(), 5), 3.81661)
  expect_equal(chi$mgf(0), 1)
  expect_equal(chi$cf(1/2), -.25)
  expect_equal(chi$mode(), 6)
  expect_equal(chi$pdf(1), dchisq(1, 8))
  expect_equal(chi$cdf(1), pchisq(1, 8))
  expect_equal(chi$quantile(.5), qchisq(.5, 8))
  expect_silent(chi$rand(10))
})