# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_Choose <- function(x, y) {
    .Call(`_distr6_C_Choose`, x, y)
}

C_NegativeBinomialPdf <- function(x, size, prob, form) {
    .Call(`_distr6_C_NegativeBinomialPdf`, x, size, prob, form)
}

C_WeightedDiscretePdf <- function(x, data, pdf, logp) {
    .Call(`_distr6_C_WeightedDiscretePdf`, x, data, pdf, logp)
}

C_Vec_WeightedDiscretePdf <- function(x, data, pdf, logp) {
    .Call(`_distr6_C_Vec_WeightedDiscretePdf`, x, data, pdf, logp)
}

C_WeightedDiscreteCdf <- function(x, data, cdf, lower, logp) {
    .Call(`_distr6_C_WeightedDiscreteCdf`, x, data, cdf, lower, logp)
}

C_Vec_WeightedDiscreteCdf <- function(x, data, cdf, lower, logp) {
    .Call(`_distr6_C_Vec_WeightedDiscreteCdf`, x, data, cdf, lower, logp)
}

C_WeightedDiscreteQuantile <- function(x, data, cdf, lower, logp) {
    .Call(`_distr6_C_WeightedDiscreteQuantile`, x, data, cdf, lower, logp)
}

C_Vec_WeightedDiscreteQuantile <- function(x, data, cdf, lower, logp) {
    .Call(`_distr6_C_Vec_WeightedDiscreteQuantile`, x, data, cdf, lower, logp)
}

C_dpq <- function(fun, x, args, lower = TRUE, log = FALSE) {
    .Call(`_distr6_C_dpq`, fun, x, args, lower, log)
}

C_r <- function(fun, x, args) {
    .Call(`_distr6_C_r`, fun, x, args)
}

