# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_Choose <- function(x, y) {
    .Call(`_distr6_C_Choose`, x, y)
}

C_ArcsinePdf <- function(x, min, max, logp) {
    .Call(`_distr6_C_ArcsinePdf`, x, min, max, logp)
}

C_ArcsineCdf <- function(x, min, max, lower, logp) {
    .Call(`_distr6_C_ArcsineCdf`, x, min, max, lower, logp)
}

C_ArcsineQuantile <- function(x, min, max, lower, logp) {
    .Call(`_distr6_C_ArcsineQuantile`, x, min, max, lower, logp)
}

C_DegeneratePdf <- function(x, mean, logp) {
    .Call(`_distr6_C_DegeneratePdf`, x, mean, logp)
}

C_DegenerateCdf <- function(x, mean, lower, logp) {
    .Call(`_distr6_C_DegenerateCdf`, x, mean, lower, logp)
}

C_DegenerateQuantile <- function(x, mean, lower, logp) {
    .Call(`_distr6_C_DegenerateQuantile`, x, mean, lower, logp)
}

C_EmpiricalMVPdf <- function(x, data) {
    .Call(`_distr6_C_EmpiricalMVPdf`, x, data)
}

C_EmpiricalMVCdf <- function(x, data) {
    .Call(`_distr6_C_EmpiricalMVCdf`, x, data)
}

C_ShiftedLoglogisticPdf <- function(x, location, shape, scale, logp) {
    .Call(`_distr6_C_ShiftedLoglogisticPdf`, x, location, shape, scale, logp)
}

C_ShiftedLoglogisticCdf <- function(x, location, shape, scale, lower, logp) {
    .Call(`_distr6_C_ShiftedLoglogisticCdf`, x, location, shape, scale, lower, logp)
}

C_ShiftedLoglogisticQuantile <- function(x, location, shape, scale, lower, logp) {
    .Call(`_distr6_C_ShiftedLoglogisticQuantile`, x, location, shape, scale, lower, logp)
}

C_WeightedDiscretePdf <- function(x, data, pdf, logp) {
    .Call(`_distr6_C_WeightedDiscretePdf`, x, data, pdf, logp)
}

C_Vec_WeightedDiscretePdf <- function(x, data, pdf, logp) {
    .Call(`_distr6_C_Vec_WeightedDiscretePdf`, x, data, pdf, logp)
}

C_WeightedDiscreteCdf <- function(x, data, cdf, lower, logp) {
    .Call(`_distr6_C_WeightedDiscreteCdf`, x, data, cdf, lower, logp)
}

C_Vec_WeightedDiscreteCdf <- function(x, data, cdf, lower, logp) {
    .Call(`_distr6_C_Vec_WeightedDiscreteCdf`, x, data, cdf, lower, logp)
}

C_WeightedDiscreteQuantile <- function(x, data, cdf, lower, logp) {
    .Call(`_distr6_C_WeightedDiscreteQuantile`, x, data, cdf, lower, logp)
}

C_Vec_WeightedDiscreteQuantile <- function(x, data, cdf, lower, logp) {
    .Call(`_distr6_C_Vec_WeightedDiscreteQuantile`, x, data, cdf, lower, logp)
}

C_NumericCdf_Discrete <- function(q, x, pdf, lower, logp) {
    .Call(`_distr6_C_NumericCdf_Discrete`, q, x, pdf, lower, logp)
}

C_NumericQuantile <- function(p, x, cdf, lower, logp) {
    .Call(`_distr6_C_NumericQuantile`, p, x, cdf, lower, logp)
}

C_CosineKernelPdf <- function(x, logp) {
    .Call(`_distr6_C_CosineKernelPdf`, x, logp)
}

C_CosineKernelCdf <- function(x, lower, logp) {
    .Call(`_distr6_C_CosineKernelCdf`, x, lower, logp)
}

C_CosineKernelQuantile <- function(x, lower, logp) {
    .Call(`_distr6_C_CosineKernelQuantile`, x, lower, logp)
}

C_EpanechnikovKernelPdf <- function(x, logp) {
    .Call(`_distr6_C_EpanechnikovKernelPdf`, x, logp)
}

C_EpanechnikovKernelCdf <- function(x, lower, logp) {
    .Call(`_distr6_C_EpanechnikovKernelCdf`, x, lower, logp)
}

C_LogisticKernelPdf <- function(x, logp) {
    .Call(`_distr6_C_LogisticKernelPdf`, x, logp)
}

C_LogisticKernelCdf <- function(x, lower, logp) {
    .Call(`_distr6_C_LogisticKernelCdf`, x, lower, logp)
}

C_LogisticKernelQuantile <- function(x, lower, logp) {
    .Call(`_distr6_C_LogisticKernelQuantile`, x, lower, logp)
}

C_NormalKernelPdf <- function(x, logp) {
    .Call(`_distr6_C_NormalKernelPdf`, x, logp)
}

C_QuarticKernelPdf <- function(x, logp) {
    .Call(`_distr6_C_QuarticKernelPdf`, x, logp)
}

C_QuarticKernelCdf <- function(x, lower, logp) {
    .Call(`_distr6_C_QuarticKernelCdf`, x, lower, logp)
}

C_SigmoidKernelPdf <- function(x, logp) {
    .Call(`_distr6_C_SigmoidKernelPdf`, x, logp)
}

C_SilvermanKernelPdf <- function(x, logp) {
    .Call(`_distr6_C_SilvermanKernelPdf`, x, logp)
}

C_SilvermanKernelCdf <- function(x, lower, logp) {
    .Call(`_distr6_C_SilvermanKernelCdf`, x, lower, logp)
}

C_TriangularKernelPdf <- function(x, logp) {
    .Call(`_distr6_C_TriangularKernelPdf`, x, logp)
}

C_TriangularKernelCdf <- function(x, lower, logp) {
    .Call(`_distr6_C_TriangularKernelCdf`, x, lower, logp)
}

C_TriangularKernelQuantile <- function(x, lower, logp) {
    .Call(`_distr6_C_TriangularKernelQuantile`, x, lower, logp)
}

C_TricubeKernelPdf <- function(x, logp) {
    .Call(`_distr6_C_TricubeKernelPdf`, x, logp)
}

C_TricubeKernelCdf <- function(x, lower, logp) {
    .Call(`_distr6_C_TricubeKernelCdf`, x, lower, logp)
}

C_TriweightKernelPdf <- function(x, logp) {
    .Call(`_distr6_C_TriweightKernelPdf`, x, logp)
}

C_TriweightKernelCdf <- function(x, lower, logp) {
    .Call(`_distr6_C_TriweightKernelCdf`, x, lower, logp)
}

C_UniformKernelPdf <- function(x, logp) {
    .Call(`_distr6_C_UniformKernelPdf`, x, logp)
}

C_UniformKernelCdf <- function(x, lower, logp) {
    .Call(`_distr6_C_UniformKernelCdf`, x, lower, logp)
}

C_UniformKernelQuantile <- function(x, lower, logp) {
    .Call(`_distr6_C_UniformKernelQuantile`, x, lower, logp)
}

C_dpq <- function(fun, x, args, lower = TRUE, log = FALSE) {
    .Call(`_distr6_C_dpq`, fun, x, args, lower, log)
}

C_r <- function(fun, x, args) {
    .Call(`_distr6_C_r`, fun, x, args)
}

